# Generated by Django 5.0.1 on 2025-12-30 17:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título de la Auditoría')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Estado')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Fecha Programada')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Puntaje Total Obtenido')),
                ('max_possible_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Puntaje Máximo Posible')),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Porcentaje de Cumplimiento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Generales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='Usuario que ejecutará la auditoría', on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_audits', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a (Auditor)')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='companies.branch', verbose_name='Sucursal')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_audits', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='audits', to='templates.audittemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'db_table': 'audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, help_text='Puntaje otorgado (0 al máximo definido en la pregunta)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Puntaje')),
                ('notes', models.TextField(blank=True, verbose_name='Notas/Observaciones')),
                ('evidence_file', models.CharField(blank=True, help_text='URL del archivo de evidencia en storage', max_length=500, verbose_name='Archivo de Evidencia (URL)')),
                ('responded_at', models.DateTimeField(auto_now_add=True, verbose_name='Respondido en')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='audits.audit', verbose_name='Auditoría')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responses', to='templates.templatequestion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Auditoría',
                'verbose_name_plural': 'Respuestas de Auditoría',
                'db_table': 'audit_responses',
                'ordering': ['audit', 'question__order_num'],
            },
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['status'], name='audits_status_7f0541_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['company'], name='audits_company_efde9f_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['scheduled_date'], name='audits_schedul_5a7ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['assigned_to'], name='audits_assigne_bcadee_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['created_by'], name='audits_created_41ca55_idx'),
        ),
        migrations.AddIndex(
            model_name='auditresponse',
            index=models.Index(fields=['audit'], name='audit_respo_audit_i_c3091f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditresponse',
            index=models.Index(fields=['question'], name='audit_respo_questio_5de632_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditresponse',
            unique_together={('audit', 'question')},
        ),
    ]
