# Generated by Django 5.0.1 on 2026-01-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditresponse',
            name='response_type',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No'), ('partial', 'Parcial'), ('na', 'No Aplica')], max_length=10, null=True, verbose_name='Tipo de Respuesta'),
        ),
    ]
