# Generated by Django 5.0 on 2025-12-30 17:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Plantilla')),
                ('iso_standard', models.CharField(help_text='Ejemplo: 27701, 9001, 27001', max_length=50, verbose_name='Estándar ISO')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Solo plantillas activas pueden usarse en auditorías', verbose_name='Activa')),
                ('version', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Versión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de Auditoría',
                'verbose_name_plural': 'Plantillas de Auditoría',
                'db_table': 'audit_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Ejemplo: Política de Privacidad, Gestión de Datos', max_length=200, verbose_name='Categoría')),
                ('question_text', models.TextField(verbose_name='Pregunta')),
                ('order_num', models.IntegerField(help_text='Orden de la pregunta dentro de la plantilla', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden')),
                ('max_score', models.IntegerField(default=5, help_text='Puntaje máximo que se puede obtener en esta pregunta', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Puntaje Máximo')),
                ('is_required', models.BooleanField(default=True, help_text='Si es obligatoria, debe responderse para completar la auditoría', verbose_name='Obligatoria')),
                ('help_text', models.TextField(blank=True, help_text='Información adicional para guiar la respuesta', verbose_name='Texto de Ayuda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='templates.audittemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Pregunta de Plantilla',
                'verbose_name_plural': 'Preguntas de Plantilla',
                'db_table': 'template_questions',
                'ordering': ['template', 'order_num'],
            },
        ),
        migrations.AddIndex(
            model_name='audittemplate',
            index=models.Index(fields=['iso_standard'], name='audit_templ_iso_sta_357303_idx'),
        ),
        migrations.AddIndex(
            model_name='audittemplate',
            index=models.Index(fields=['is_active'], name='audit_templ_is_acti_36e9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='audittemplate',
            index=models.Index(fields=['created_by'], name='audit_templ_created_b4f30b_idx'),
        ),
        migrations.AddIndex(
            model_name='templatequestion',
            index=models.Index(fields=['template', 'order_num'], name='template_qu_templat_360e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='templatequestion',
            index=models.Index(fields=['category'], name='template_qu_categor_b3c46a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templatequestion',
            unique_together={('template', 'order_num')},
        ),
    ]
