# Generated by Django 5.0.1 on 2025-12-30 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Comparación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Comparación',
                'verbose_name_plural': 'Comparaciones',
                'db_table': 'comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Orden de la auditoría en la comparación', verbose_name='Orden')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.audit', verbose_name='Auditoría')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparisons.comparison', verbose_name='Comparación')),
            ],
            options={
                'db_table': 'comparison_audits',
                'ordering': ['order'],
                'unique_together': {('comparison', 'audit')},
            },
        ),
        migrations.AddField(
            model_name='comparison',
            name='audits',
            field=models.ManyToManyField(related_name='comparisons', through='comparisons.ComparisonAudit', to='audits.audit', verbose_name='Auditorías'),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='Categoría')),
                ('recommendation_text', models.TextField(verbose_name='Texto de Recomendación')),
                ('priority', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], max_length=20, verbose_name='Prioridad')),
                ('is_auto_generated', models.BooleanField(default=False, help_text='True si fue generada por el sistema', verbose_name='Generada Automáticamente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='audits.audit', verbose_name='Auditoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
                'db_table': 'recommendations',
                'ordering': ['audit', '-priority', 'category'],
            },
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['created_by'], name='comparisons_created_a01de5_idx'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['created_at'], name='comparisons_created_b01416_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['audit'], name='recommendat_audit_i_72489e_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['priority'], name='recommendat_priorit_8d706b_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['is_auto_generated'], name='recommendat_is_auto_358b25_idx'),
        ),
    ]
